name: airflow
version: 0.0.3
appVersion: 1.10.2
description: Helm chart to deploy Airflow with K8s executors
keywords:
  - airflow
  - apache
home: https://airflow.apache.org/
sources:
- https://github.com/tekn0ir/airflow-chart
maintainers:
- name: tekn0ir
  email: anders.aslund@teknoir.se
engine: gotpl
